#locale: en

storage:
  # Available (case-insensitive): h2, sqlite, mysql, mariadb or postgresql
  storage-method: sqlite

  # H2, SQLite section
  file: database.db

  # MySQL, MariaDB, PostgreSQL section
  host: localhost
  port: 3306
  database: thimble
  username: thimble
  password: password

# Alternate command names
aliases: [th]

# Enabled integrations with other plugins.
integrations:
 - LuckPerms
 - Parties
 - PlaceholderAPI
 - WorldEdit

game:
  # If the player's inventory should be cleared when joining the arena.
  # You might need to disable this if you have an inventory plugin - the inventory is restored at the end of the game.
  clear-inventory: true

  # If players lose points in concurrent mode when the jump is failed.
  count-fails-concurrent: false

  # If enabled, players will be teleported to the arena spawn rather than to their previous position.
  teleport-at-end: false

  # The duration of the countdown, where other players can still join the arena.
  countdown-time: 30

  # The delay in seconds before players are kicked from the arena at the end of a game.
  end-time: 5

  # Maximum duration (in sec) of each jump in single mode before the player loses a life.
  jump-time-single: 15

  # Time players have to make a maximum number of jumps in concurrent mode.
  jump-time-concurrent: 40

  # Extra points with a thimble in concurrent mode.
  thimble-points-concurrent: 1

  # Set the number of fireworks to be thrown during a thimble and at the end of a game.
  fireworks-thimble: 1
  fireworks-end: 4

  # Write an inventory backup to the disk before the player's inventory is cleared.
  # Inventories will still be saved in memory, but may be lost due to a crash.
  save-states-in-file: true

  # If enabled, the plugin will consider that teleporting out of the arena makes you quit the game.
  # If the cause of the teleportation is "COMMAND" then the player will always leave the arena.
  leave-arena-when-tp: true

  # If enabled, when a player leaves the server, he also leaves the game.
  quit-game-on-disconnect: false

  # Ignore the statistics if the player is alone in the arena or is the only one who jumped.
  ignore-stats-if-solo: true

  # When a player loses, his game mode is set to spectator.
  spectator-mode: true

  # Set the maximum distance (x and z coordinates) that spectators can have from the waiting location.
  max-spectator-distance: 40

# The countdown display.
display:
  global:
    type: bossbar
    bossbar-color: yellow
    bossbar-overlay: progress
  jump:
    type: bossbar
    bossbar-color: red
    bossbar-overlay: progress

# Sounds used. https://minecraft.gamepedia.com/Sounds.json#Sound_events
#sound:
#  jump-failed: entity.player.hurt
#  jump-succeed: block.note_block.xylophone
#  thimble: entity.experience_orb.pickup
#  countdown: block.note_block.harp

# List of blocks that the player can choose. This accepts regex.
# https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
blocks:
  - ".*WOOL"
  - ".*_TERRACOTTA"

# List of clickable elements. As the text of a clickable sign is no longer used once created,
# it can be replaced by any other clickable block with `/setblock` and keep its behavior.
clickable:
  - ".*_BUTTON"
  - ".*SIGN"

# If the arena signs should be updated with the game state.
update-signs: true

# Lists the commands allowed when the player is in the game.
# Users with the thimble.restrictions.bypass permission are exempt.
allowed-commands-in-game:
  - thimble
  - th
  - msg
  - tell

# Defines whether the plugin checks at server startup if it is up-to-date.
# You can also use '/th version' to check the version and update.
update-checker: true
