locale: en

# Available (case-insensitive): sqlite, mysql or postgre
storage-method: sqlite

sql:
  # When SQLite is used, the following parameters are not necessary.
  # JDBC uri format: jdbc:driver://host:port/database
  # MySQL/MariaDB driver: mysql, PostgreSQL driver: postgresql
  jdbcUri: jdbc:mysql://localhost:3306/decoudre
  username: decoudre
  password: password

integrations:
 - PlaceholderAPI

game:
  teleport-at-end: true
  countdown-time: 30
  jump-time: 15

display:
  global:
    type: bossbar
    bossbar-color: yellow
    bossbar-overlay: progress
  jump:
    type: bossbar
    bossbar-color: red
    bossbar-overlay: progress
